### ISSUE TITLE
需要添加一个回收密码的函数

### ISSUE THREAD

**Issue by yuanbinyao** [MXWXZ/FuckBaiduPanPwd#6]
最近百度似乎改了一些东西，导致大量的POST request返回的不是-9(密码错误)而是-62(达到密码次数上限)。这种情况下很多密码在不知道对错的情况下从字典里移除，很可能错过正确密码。
不改代码的解决方法是频繁的关闭/重启程序。因为只有-9的结果才会写进log，所以写进log里面的肯定是错的，这样可以减少误删除的密码量
改动的办法是加一个回收函数，在结果既不是-9也不是0的情况下把尝试的密码重新加回字典。
我写了一个正在我机子上试验，如果成功的话我回头会提交一个PR

**Comment by JackChou1996** [comment]
{"errno":2,"request_id":575938070893026579}
我这边用了verify 出来errorno 是2

**Comment by yuanbinyao** [comment]
> {"errno":2,"request_id":575938070893026579} 我这边用了verify 出来errorno 是2

2的话我自己没见过，我搜到的有说是参数错误，有说是分享次数达到上限。
我的PR里面只要不是-9或者0都会被重新放进密码池中，所以具体errorno是什么并不重要

**Comment by HahaMDC** [comment]
您好，这位朋友，能够请您直接帮我跑开一个云盘链接吗？我是电脑小白，这个代码库怎么导入程序并运行的我完全不懂……我热心希望您能直接帮助我一下，当然不是无偿请您帮助，不知道什么时候能够和您取得联系……我一直在等待……请问您的邮箱是什么？希望您能看到这条短信

**Comment by yuanbinyao** [comment]
> 您好，这位朋友，能够请您直接帮我跑开一个云盘链接吗？我是电脑小白，这个代码库怎么导入程序并运行的我完全不懂……我热心希望您能直接帮助我一下，当然不是无偿请您帮助，不知道什么时候能够和您取得联系……我一直在等待……请问您的邮箱是什么？希望您能看到这条短信

这个很简单，只需要安装Python，然后运行crack.py这个python脚本，然后按着要求输入信息就行了
另外百度现在肯定是做了调整，大部分时间返回的都是无效的错误代码(-62，-64或者-65)，运气不好的话可能需要很久才能测出来。所以这个忙我真的没法帮

**Comment by HahaMDC** [comment]
谢谢您回复我，遗憾的是，您说的简单对我来说并不简单，我这个电脑小白真的就只是小白，这个什么Python程序是什么我也不懂，登录上github对我来说都很困难了，所以我希望找一个电脑高手亲自动手解决我的问题，再次感谢你

**Comment by aelharda** [comment]
@yuanbinyao  was the change you suggest above worked? if yes, do you mind sending me your version? Thanks

**Comment by yuanbinyao** [comment]
> @yuanbinyao was the change you suggest above worked? if yes, do you mind sending me your version? Thanks

You can find my version in the fork
Frankly speaking it doesn't work well now. Based on my observation Baidu instates some restriction in the backend and only very limited requests would return -9 (which tell you what pwd is really wrong). Other requests return something else (mostly -62 and -64, sometimes no errno) which you cannot tell whether it is pwd or not (In some cases even correct pwd would return these 2 errno).
As the restriction is on backend, I don't see a way to crack it yet. So it may take a very very very long time (dozes months? and you have to keep restarting this script) to really hack one which I doubt whether it worths on the time bases
